<?xml version="1.0" ?>
<robot name="planar" xmlns:xacro="http://ros.org/wiki/xacro">
 

 <xacro:include filename="$(find robot2_description)/urdf/robot2_2.xacro" />
    

 <link name="world">
 </link>
 
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  <material name="grey">
    <color rgba="0.4 0.4 0.4 1.0" />
  </material>

 <joint name="bottom_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="world"/>
    <child link="base_link"/>
  </joint>
  


    
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_width}  ${base_width} ${base_height}"/>
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
             <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_width}  ${base_width} ${base_height}" />
           </geometry>
        </collision>
         <xacro:inertial_box mass="4" x="${base_width} " y="${base_width} " z="${base_height} ">
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
   	<gazebo reference="base_link">
    		<material>Gazebo/Black</material>
  	</gazebo>
  
  
 	<xacro:joint_revolute_z joint_name="axis_2_joint" parent_link ="base_link" 
			child_link ="axis_2_link">
	 	<origin xyz="${base_width/2}  0 ${base_height/2}" rpy="0 0 0"/>
	</xacro:joint_revolute_z>
  
	 <!-- Axis_2 Link-->
 	<link name="axis_2_link"> 
		<xacro:cylinder_visual_collision_white radius ="${axis_2_radius}" length ="${axis_2_height}">
		<origin  xyz="${axis_2_height/2} 0 0" rpy="0 1.5708 0"/>
		</xacro:cylinder_visual_collision_white>
	 	<xacro:inertial_cylinder mass="4" length = "${axis_2_height}" radius ="${axis_2_radius}">
           <origin  xyz="${axis_2_height/2} 0 0" rpy="0 1.5708 0 "/>
        	</xacro:inertial_cylinder>
	</link>
	
	
	
	<xacro:joint_revolute_z joint_name="axis_3_joint" parent_link ="axis_2_link" 
		child_link ="axis_3_link">
	 <origin xyz="${axis_2_height}  0 0" rpy="0 0 0"/>
	</xacro:joint_revolute_z>
	
	
	 <!-- Axis_2 Link-->
 	<link name="axis_3_link"> 
		<xacro:cylinder_visual_collision_white radius ="${axis_2_radius}" length ="${axis_3_height}">
		<origin  xyz="${axis_3_height/2} 0 0" rpy="0 1.5708 0"/>
		</xacro:cylinder_visual_collision_white>
	 	<xacro:inertial_cylinder mass="4" length = "${axis_3_height}" radius ="${axis_2_radius}">
           <origin  xyz="${axis_3_height/2} 0 0" rpy="0 1.5708 0"/>
        	</xacro:inertial_cylinder>
	</link>
	
  
  
	<xacro:transmission joint_name="axis_2_joint">
	</xacro:transmission>
	<xacro:transmission joint_name="axis_3_joint">
	</xacro:transmission>



  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
          <robotNamespace>/planar</robotNamespace>
     <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>
  
</robot>	

