<?xml version="1.0" ?>
<robot name="robot2" xmlns:xacro="http://ros.org/wiki/xacro">
 

 <xacro:include filename="$(find robot2_description)/urdf/robot2_2.xacro" />
    

 <link name="world">
 </link>
 
 <!-- joint name="bottom_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="world"/>
    <child link="base_link"/>
  </joint -->
  

 
    <!-- base_link is a large rectangular plate. Some things to note: -->
    <!-- - We set the visual origin Z to half the box height, so that the link origin sits at the bottom of the box -->
    
    <!--link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_width}  ${base_width} ${base_height}"/>
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
             <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_width}  ${base_width} ${base_height}" />
           </geometry>
        </collision>
         <xacro:inertial_box mass="4" x="${base_width} " y="${base_width} " z="${base_height} ">
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link -->
    
   	<gazebo reference="base_link">
    		<material>Gazebo/Black</material>
  	</gazebo>
  
  
 	<!--xacro:joint_revolute_z joint_name="base_joint" parent_link ="base_link" 
			child_link ="axis_2_link">
	 	<origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
	</xacro:joint_revolute_z-->
  
	

	 <!-- Axis_2 Link-->
 	<!--link name="axis_2_link"> 
		<xacro:cylinder_visual_collision_white radius ="${axis_2_radius}" length = "${axis_2_height}">
		<origin  xyz="0 0 ${axis_2_height/2}" rpy="0 0 0"/>
		</xacro:cylinder_visual_collision_white>
	 	<xacro:inertial_cylinder mass="4" length = "${axis_2_height}" radius ="${axis_2_radius}">
           <origin  xyz="0 0 ${axis_2_height/2}" rpy="0  ${45*deg_to_rad} 0"/>
        	</xacro:inertial_cylinder>
	</link-->

 	<!--joint name="axis_2_joint" type="fixed">
   	 <origin xyz="0 0 ${axis_2_height} " rpy="0 0 0" />
    	<parent link="axis_2_link"/>
    	<child link="axis_3_link"/>
  	</joint-->

	 <!-- Axis_3 Link-->

 	<!--link name="axis_3_link"> 
		<xacro:cylinder_visual_collision_red radius ="${axis_2_radius}" length = "${axis_3_height}">
		<origin  xyz="0 0 ${axis_3_height/2}" rpy="0 0  0"/>
		</xacro:cylinder_visual_collision_red>
		 <xacro:inertial_cylinder mass="1.5" length = "${axis_3_height}" radius ="${axis_2_radius}">
           	<origin  xyz="0 0 ${axis_3_height/2}" rpy="0  0 0"/>
       	 </xacro:inertial_cylinder>
	</link-->	 

 	<xacro:joint_revolute_y joint_name="axis_3_joint" parent_link ="world" 
		child_link ="axis_4_link">
	 <origin xyz="0 ${axis_4_height} ${axis_2_radius}" rpy="0 ${-90*deg_to_rad} 0"/>
	</xacro:joint_revolute_y>
	 
	 <!--xacro:joint_revolute_y joint_name="axis_3_joint" parent_link ="axis_3_link" 
		child_link ="axis_4_link">
	 <origin xyz="0 0 ${axis_3_height}" rpy="0 ${-90*deg_to_rad} 0"/>
	</xacro:joint_revolute_y-->
	 
	 <!-- Axis_4 Link-->

 	<link name="axis_4_link"> 
	<xacro:cylinder_visual_collision_white radius ="${axis_2_radius}" length = "${axis_4_height}">
	<origin  xyz="0  ${axis_4_height/2}   ${axis_2_radius} " rpy="0 0  0"/>
	</xacro:cylinder_visual_collision_white>
	 <xacro:inertial_cylinder mass="1.2" length = "${axis_4_height}" radius ="${axis_2_radius}">
           <origin  xyz="0 ${axis_4_height/2} ${axis_2_radius}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
	</link>	
	
	<!--link name="axis_4_link"> 
	<xacro:cylinder_visual_collision_white radius ="${axis_2_radius}" length = "${axis_4_height}">
	<origin  xyz="0 0 ${axis_4_height/2}" rpy="0 0  0"/>
	</xacro:cylinder_visual_collision_white>
	 <xacro:inertial_cylinder mass="1.2" length = "${axis_4_height}" radius ="${axis_2_radius}">
           <origin  xyz="0 0 ${axis_4_height/2}" rpy="0  0 0"/>
        </xacro:inertial_cylinder>
	</link-->	 

 	<!--xacro:joint_revolute_y joint_name="axis_4_joint" parent_link ="axis_4_link" 
		child_link ="axis_5_link">
	 <origin xyz="0 0 ${axis_4_height}" rpy="0 0 0"/>
	</xacro:joint_revolute_y-->
	
	<!--xacro:joint_revolute_y joint_name="axis_4_joint" parent_link ="axis_4_link" 
		child_link ="axis_5_link">
	 <origin xyz="${axis_4_height} 0  0 " rpy="0 0 0"/>
	</xacro:joint_revolute_y-->
	 
		 <!-- Axis_5 Link-->

	<!--link name="axis_5_link"> 
	<xacro:cylinder_visual_collision_red radius ="${axis_2_radius}" length = "${axis_5_height}">
	<origin  xyz="0 0 ${axis_5_height/2}" rpy="0 0  0"/>
	</xacro:cylinder_visual_collision_red>
	 <xacro:inertial_cylinder mass="1" length = "${axis_5_height}" radius ="${axis_2_radius}">
           <origin  xyz="0 0 ${axis_5_height/2}" rpy="0  0 0"/>
        </xacro:inertial_cylinder>
	</link-->
	
	
 	<!--link name="axis_5_link"> 
	<xacro:cylinder_visual_collision_red radius ="${axis_2_radius}" length = "${axis_5_height}">
	<origin  xyz="0  ${axis_5_height/2} 0 " rpy="0 0  0"/>
	</xacro:cylinder_visual_collision_red>
	 <xacro:inertial_cylinder mass="1" length = "${axis_5_height}" radius ="${axis_2_radius}">
           <origin  xyz="0 ${axis_5_height/2} 0" rpy="0  0 0"/>
        </xacro:inertial_cylinder>
	</link-->
	
	
	<xacro:transmission joint_name="axis_3_joint">
	</xacro:transmission>
	<!--xacro:transmission joint_name="axis_4_joint">
	</xacro:transmission-->



  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
          <robotNamespace>/robot2</robotNamespace>
     <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>
  
</robot>	
