robot2:
# Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------
  joint2_effort_controller:  
    type: effort_controllers/JointEffortController
    joint: axis_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: axis_4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}


  joint2_position_controller:  
    type: effort_controllers/JointPositionController
    joint: axis_3_joint
    pid: {p: 1000.0, i: 0.01, d: 100.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: axis_4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}


