PERA:
# Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200  
  
  # Position Controllers ---------------------------------------
  joint1_effort_controller:  
    type: effort_controllers/JointEffortController
    joint: arm_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: arm_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: arm_joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}


  joint1_position_controller:  
    type: effort_controllers/JointPositionController
    joint: arm_joint1
    pid: {p: 1000.0, i: 0.01, d: 100.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}

